spring:
  application:
    name: shop-product-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop-product?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true